src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_MerchandiseOperations.cls
/**
 * Executing Data Operations as Single Transactions
 * @see Apex Workbook, page 49
 **/
public class WARE_MerchandiseOperations 
{
	private static void addLineItem(Id invoiceId, Id merchandiseId, Decimal price, Integer quantitySold)
	{
		Line_Item__c lineItem = new Line_Item__c (								// Add a new line item to the invoice 
				name 			= '1',
				invoice__c 		= invoiceId,
				merchandise__c  = merchandiseId,
				unit_price__c	= price,
				quantity__c		= quantitySold
			); 
		try { insert lineItem; }
		catch (DmlException e) { throw new WARE_LineItemException('Line item could not be inserted.', e); }
	}
	
	private static Id createInvoice(Merchandise__c merchandise, String productDescription, Integer productSold)
	{
		Invoice__c invoice = new Invoice__c(Description__C = productDescription);		
			insert invoice;																// Add a new invoice														
		
		try 
		{ 
				addLineItem(invoice.id, merchandise.id, merchandise.price__c, productSold); 	// Add a new line item to the invoice
				merchandise.quantity__c -= productSold; 										// Update the inventory of the merchandise item			  
				update merchandise;
				return invoice.id;
		}
		catch (WARE_LineItemException lie) 
		{
			 WARE_WarehouseException.debug(lie);
			 throw new WARE_InvoiceException('Invoice could not be inserted.', lie); 
		}
	}
	
	public static Id createInvoice (String productName, Integer productSold, String productDescription)
	{
		// Retrieve the products sample merchandise
		Merchandise__c merchandise = [
										SELECT price__c, quantity__c
										FROM Merchandise__c
										WHERE name = :productName
										LIMIT 1
									];
		System.assertNotEquals(null, merchandise);										// break if no merchandise is found
		
		return createInvoice(merchandise, productDescription, productSold);
	}
}