src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_MerchandiseOperationsTest.cls
/**
 * Unit tests for WARE_MerchandiseOperations (Executing Data Operations as Single Transactions)
 * @see Apex Workbook, page 49
 **/
 @isTest
private class WARE_MerchandiseOperationsTest 
{
    public static final User TestRunner = TEST_RunAsUserFactory.create();

	private static Id doCreateInvoice (String productName, Integer productSold, String productDescription)
	{
		Id invoiceId = null;
        System.runAs(TestRunner)
        {
            Test.startTest();
            {
                invoiceId = WARE_MerchandiseOperations.createInvoice(productName, productSold, productDescription);
            }
            Test.stopTest();
        }
        return invoiceId;
	}
	
	private static Id prepCreateInvoiceTest(TEST_UniqueHelper unique, Boolean hasEnough)
	{
		String  productName 		= unique.uniqueString;
		Integer productSold 		= unique.uniqueInt;
		String  productDescription  = 'Description of ' + productName;
		
		TEST_dummyMerchandiseFactory.Config config = new TEST_dummyMerchandiseFactory.Config();
									 		config.name = productName;
									 		config.quantity = (hasEnough) ? (productSold) : (productSold - 1); 
		Merchandise__c dummyMerchandise = TEST_dummyMerchandiseFactory.createDummy(config, true);
		
		return doCreateInvoice (productName, productSold, productDescription); 
	}
	
	private static testMethod void hasEnoughTest()
	{
		TEST_UniqueHelper unique = new TEST_UniqueHelper('Product With Enough');

		Id invoiceId = prepCreateInvoiceTest(unique, true);
		System.assertNotEquals (null, invoiceId); 

		List<Line_Item__c> lineItem = [SELECT id FROM Line_Item__C WHERE Invoice__c = : invoiceId];
		System.assertEquals (1, lineItem.size());
	}

	private static testMethod void notEnoughTest()
	{
		TEST_UniqueHelper unique = new TEST_UniqueHelper('Product Without Enough');
		Id invoiceId = null;
		Boolean exceptionCaught = false;
		try { invoiceId = prepCreateInvoiceTest(unique, false); }
		catch (WARE_InvoiceException ie)
		{
			System.assertEquals (null, invoiceId);
			exceptionCaught = true; 
		}
		System.assert(exceptionCaught);
	}
}