src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_MerchandiseCleanTestLists.cls
/**
 * Unit Tests for example of Apex Batch Processing
 * @see Apex Workbook, page 65
 **/
@isTest
public class WARE_MerchandiseCleanTestLists
{
    	public List<Merchandise__c> dummyMerchandiseNotInLineItemsList = null;
    	public List<Merchandise__c> dummyMerchandiseInLineItemsList    = null;
    	
    	public WARE_MerchandiseCleanTestLists() {}
    	
    	public WARE_MerchandiseCleanTestLists(Integer numberOfMerchandiseNotInLineItems, Integer numberOfMerchandiseInLineItems)
    	{
			// Create some test merchandise items to be deleted by the batch job.
			this.dummyMerchandiseNotInLineItemsList = TEST_DummyMerchandiseFactory.createDummyList(numberOfMerchandiseNotInLineItems, true);
	
			// Create some test merchandise items to be kept after the batch job (to test against false positives).
			this.dummyMerchandiseInLineItemsList 	= TEST_DummyMerchandiseFactory.createDummyList(numberOfMerchandiseInLineItems, true);
			addLineItemsForMerchandise(this.dummyMerchandiseInLineItemsList);
	    }

		private static void addLineItemsForMerchandise(List<Merchandise__c> merchandiseList)
		{
			List<Invoice__c> dummyInvoiceInLineItemsList 			= TEST_DummyInvoiceFactory.createDummyList(merchandiseList.size(), true);
	
			List<Line_Item__c> dummyLineItemList = new List<Line_Item__c>();
			Integer i = 0;
			for (Merchandise__c dummyMerchandise : merchandiseList)
			{
				dummyLineItemList.add(TEST_DummyLineItemFactory.createDummy(dummyInvoiceInLineItemsList[i], dummyMerchandise , false));
				i++;
			}
			
			insert dummyLineItemList;
		}

}