src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BAT_CleanUpRecordsTest.cls
/**
 * Unit Tests for example of Apex Batch Processing
 * @see Apex Workbook, page 65
 **/
 @isTest
private class BAT_CleanUpRecordsTest 
{
    public static final User TestRunner = TEST_RunAsUserFactory.create();
    
	private static testMethod void batchTest()
	{
		// The query used by the batch job.
		String query = 'SELECT id, createdDate FROM Merchandise__c WHERE id NOT IN (SELECT Merchandise__c FROM Line_Item__c)';

		WARE_MerchandiseCleanTestLists merchandiseTestLists = new WARE_MerchandiseCleanTestLists (10, 10); 

		List<Merchandise__c> dummyMerchandiseNotInLineItemsList = merchandiseTestLists.dummyMerchandiseNotInLineItemsList;
		List<Merchandise__c> dummyMerchandiseInLineItemsList 	= merchandiseTestLists.dummyMerchandiseInLineItemsList; 
				
        System.runAs(TestRunner)
        {
            Test.startTest();
            {
                BAT_CleanUpRecords cleanRecords = new BAT_CleanUpRecords(query);
                Database.executeBatch(cleanRecords);
            }
            Test.stopTest();
        }
        
        TEST_DummyMerchandiseFactory.assertMerchandise (dummyMerchandiseNotInLineItemsList, false); // Verify merchandise items without line items got deleted.
		TEST_DummyMerchandiseFactory.assertMerchandise (dummyMerchandiseInLineItemsList, true);     // Verify merchandise items with line items did not get deleted.
	}
	
}