src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_InsertMerchandiseScheduler.cls
/**
 * For Scheduled Execution of Apex
 * @see Apex Workbook, page 60.
 **/
global class WARE_InsertMerchandiseScheduler implements Schedulable 
{
    public static final String SCHEDULED_MERCHANDISE_NAME = 'Scheduled Job Item';
    global void execute (SchedulableContext context)
    {
        CronTrigger cronTrigger = [
                                    SELECT id, cronExpression, timesTriggered, nextFireTime
                                    FROM CronTrigger
                                    WHERE id = :context.getTriggerId()
                                ];
                                
        System.debug(LoggingLevel.INFO, cronTrigger.cronExpression);
        System.debug(LoggingLevel.INFO, cronTrigger.timesTriggered);
        
        Merchandise__c merchandise = new Merchandise__c (
                                            name            = SCHEDULED_MERCHANDISE_NAME,
                                            description__c  = 'Created by the scheduler',
                                            price__c        = 1,
                                            quantity__c     = 1000
                                );
                insert merchandise;
    }
}