src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_DisplayMerchandise.cls
/**
 *	Once-Inner class to hold online store details for each merchandise item.  
 * 	(Moved to seperate class because I prefer shorter classes and code reuse.)
 *  Example Visualforce Pages with Apex Controllers
 *  @See Apex Workbook, page 73 
 **/
public class WARE_DisplayMerchandise 
{
	// Properties for use in the VisualForce view
	public String  name 	     { get { return merchandise.name; 		       } }
	public String  description   { get { return merchandise.description__c;    } }
	public Decimal price         { get { return merchandise.price__c; 	       } }
	public Boolean inStock	   	 { get { return (0 < merchandise.quantity__c); } }
	public Integer quantityToBuy { get; set; }

	private Merchandise__c merchandise;
	
	public WARE_DisplayMerchandise(Merchandise__c merchandise) { this.merchandise = merchandise; }

	public static Map<id,WARE_DisplayMerchandise> buildMap (List<WARE_DisplayMerchandise> displayMerchandiseList)
	{
		Map<id,WARE_DisplayMerchandise> merchandiseMap = new Map<id,WARE_DisplayMerchandise>(); 
		
		for (WARE_DisplayMerchandise displayMerchandise : displayMerchandiseList)
		{
			merchandiseMap.put(displayMerchandise.merchandise.id, displayMerchandise);
		}
		
		return merchandiseMap;
	}	
}