src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WARE_DisplayMerchandiseTest.cls
/**
 *	Unit Tests for Once-Inner class to hold online store details for each merchandise item.  
 * 	(Moved to seperate class because I prefer shorter classes and code reuse.)
 *  Example Visualforce Pages with Apex Controllers
 *  @See Apex Workbook, page 73 
 **/
 @isTest
public class WARE_DisplayMerchandiseTest 
{
    public static final User TestRunner = TEST_RunAsUserFactory.create();

	private static testMethod void buildMapTest()
	{
		List<Merchandise__c> merchandiseList = TEST_DummyMerchandiseFactory.createDummyList(10, true);
		List<WARE_DisplayMerchandise> displayMerchandiseList = createDummyList (merchandiseList);
		
		Map<id,WARE_DisplayMerchandise> displayMerchandiseMap = null;
        System.runAs(TestRunner)
        {
            Test.startTest();
            {
                 displayMerchandiseMap = WARE_DisplayMerchandise.buildMap (displayMerchandiseList);
            }
            Test.stopTest();
        }

		assertEquivalent (merchandiseList, displayMerchandiseMap);
	}

	public static List<WARE_DisplayMerchandise> createDummyList(List<Merchandise__c> merchandiseList)
	{
		List<WARE_DisplayMerchandise> displayMerchandiseList = new List<WARE_DisplayMerchandise>();
		for (Merchandise__c merchandise : merchandiseList) { displayMerchandiseList.add(new WARE_DisplayMerchandise(merchandise)); }
		return displayMerchandiseList;
	}

	public static List<WARE_DisplayMerchandise> createDummyList()
	{
		List<Merchandise__c> merchandiseList = TEST_DummyMerchandiseFactory.createDummyList(10, true);
		return createDummyList (TEST_DummyMerchandiseFactory.createDummyList(10, true));
	}
	
	public static void assertEquivalent (List<Merchandise__c> merchandiseList, Map<id,WARE_DisplayMerchandise> displayMerchandiseMap)
	{
		for (Merchandise__c merchandise : merchandiseList)
		{
			WARE_DisplayMerchandise displayMerchandise = displayMerchandiseMap.get(merchandise.id);

			System.assertEquals (merchandise.name, 			 	 displayMerchandise.name		);
			System.assertEquals (merchandise.description__c, 	 displayMerchandise.description	);
			System.assertEquals (merchandise.price__c, 		 	 displayMerchandise.price		);
			System.assertEquals ((merchandise.quantity__c > 0),	 displayMerchandise.inStock		);
		}		 
	}
	
}