src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/REST_MerchandiseManager.cls
/**
 * Examples of Apex Rest
 * @see Apex Workbook, page 69.
 **/
@RestResource (urlMapping='/Merchandise/*')
global with sharing class REST_MerchandiseManager 
{
	@HttpGet
	global static Merchandise__c getMerchandiseById()
	{
		RestRequest request  = RestContext.request;
		String merchandiseId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
		Merchandise__c result = [SELECT name, description__c, price__c, quantity__c FROM Merchandise__c WHERE id = :merchandiseId];
			    return result;
	}
	
	@HttpPost
	global static String createMerchandise (String name, String description, Decimal price, Double inventory)
	{
		Merchandise__c merchandise = new Merchandise__c (
												name 			= name,
												description__c  = description,
												price__c		= price,
												quantity__c		= inventory
											);
				insert merchandise;
			    return merchandise.id;
	}
}